# Generated by Django 4.1.1 on 2022-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userprofile_facebook_url_userprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile/profile1.png', null=True, upload_to='images/profile/'),
        ),
    ]
